# This file was generated by GoReleaser. DO NOT EDIT.
cask "newsletter-cli" do
  name "newsletter-cli"
  desc "A beautiful, privacy-friendly CLI tool to analyze and unsubscribe from newsletters."
  homepage "https://github.com/loickal/newsletter-cli"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "newsletter-cli"

  on_macos do
    on_intel do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "2e8ccfb16aa3838ac4c245cdce9620a132fd9a8656cbb75bd357e4d0c92bf679"
    end
    on_arm do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "f45f25042d8b4fa15fd56170b9ac930e8d9c7243b966900fc35152722b099914"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "5a8e16ce521e8c7f3728b91e20e8e183ab9148eb9145e3b2f4c133d9431eded5"
    end
    on_arm do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "1216073ac8272769337888e2ca16e30d7dab78e4da13ac6a929cfe6ed2d878e2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/newsletter-cli"]
    end
  end

  # No zap stanza required
end
