# This file was generated by GoReleaser. DO NOT EDIT.
cask "newsletter-cli" do
  name "newsletter-cli"
  desc "A beautiful, privacy-friendly CLI tool to analyze and unsubscribe from newsletters."
  homepage "https://github.com/loickal/newsletter-cli"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "newsletter-cli"

  on_macos do
    on_intel do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "0f0719b97a946115641b1e99793e506cd88a92d308d920f7107f72a2ed4b8908"
    end
    on_arm do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "25f3abc6481d23361df4a847797258ef8e86471e750b906a16bb70fa0b373e8d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "2b738fc74717457e8d94b497ffd9965a61e37582253b45b4802bd5194edc7095"
    end
    on_arm do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "1f8fc7e4a03d7b17178d1a35e29de9a302fce482a9b75966ca73cb23c24b2d45"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/newsletter-cli"]
    end
  end

  # No zap stanza required
end
