# This file was generated by GoReleaser. DO NOT EDIT.
cask "newsletter-cli" do
  name "newsletter-cli"
  desc "A beautiful, privacy-friendly CLI tool to analyze and unsubscribe from newsletters."
  homepage "https://github.com/loickal/newsletter-cli"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "newsletter-cli"

  on_macos do
    on_intel do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "9d1b9571c66825bb1fe83b25138ec51c2760d9a2aac069d04cf4d9d690e881d3"
    end
    on_arm do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "6132db755089035be64c8440b378890df12fa6ac3db799373856736224d24ced"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "74e205e0357e070f0cebdbf108f258a89b7094f79b64d7aeb9055aae20877399"
    end
    on_arm do
      url "https://github.com/loickal/newsletter-cli/releases/download/v#{version}/newsletter-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/loickal/newsletter-cli"
      sha256 "f37045f31f9da47465be0bca54c1c04af7131ec56911e9447d1e698c8394fe40"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/newsletter-cli"]
    end
  end

  # No zap stanza required
end
